### ISSUE TITLE
java.lang.RuntimeException: Using the text recognition mode without an OCR build is not supported

### ISSUE THREAD

**Issue by ferrygun** [Scandit/barcodescanner-sdk-cordova#213]
I am trying to build the cordova app for OCR recognition. I am following this [tutorial ](https://docs.scandit.com/stable/phonegap/cordova-examples.html) but got the following error:
--------- beginning of crash
01-18 13:56:27.017 18890-18986/com.scandit.helloworld E/AndroidRuntime: FATAL EXCEPTION: engine thread
    Process: com.scandit.helloworld, PID: 18890
    java.lang.RuntimeException: Using the text recognition mode without an OCR build is not supported
        at com.scandit.barcodepicker.internal.ocr.TextScanner.processFrameAsync(TextScanner.java:35)
        at com.scandit.barcodepicker.internal.EngineThread.processFrame(EngineThread.java:533)
        at com.scandit.barcodepicker.internal.EngineThread.access$1500(EngineThread.java:88)
        at com.scandit.barcodepicker.internal.EngineThread$EngineHandler.handleMessage(EngineThread.java:1086)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

What was missing?

**Comment by moritzhartmeier** [comment]
There is a special build for OCR that is not available by default for new accounts. Please contact us at support@scandit.com to get your account upgraded to be able to use OCR.
