### ISSUE TITLE
Error while android build

### ISSUE THREAD

**Issue by avnish90** [Scandit/barcodescanner-sdk-cordova#252]
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :ScanditBarcodeScanner:.
  Searched in the following locations:
      file:/Library/Android/sdk/extras/m2repository//ScanditBarcodeScanner//ScanditBarcodeScanner-.pom
      file:/Library/Android/sdk/extras/m2repository//ScanditBarcodeScanner//ScanditBarcodeScanner-.aar
      file:/Library/Android/sdk/extras/google/m2repository//ScanditBarcodeScanner//ScanditBarcodeScanner-.pom
      file:/Library/Android/sdk/extras/google/m2repository//ScanditBarcodeScanner//ScanditBarcodeScanner-.aar
      file:/Library/Android/sdk/extras/android/m2repository//ScanditBarcodeScanner//ScanditBarcodeScanner-.pom
      file:/Library/Android/sdk/extras/android/m2repository//ScanditBarcodeScanner//ScanditBarcodeScanner-.aar
      https://maven.google.com//ScanditBarcodeScanner//ScanditBarcodeScanner-.pom
      https://maven.google.com//ScanditBarcodeScanner//ScanditBarcodeScanner-.aar
      https://jcenter.bintray.com//ScanditBarcodeScanner//ScanditBarcodeScanner-.pom
      https://jcenter.bintray.com//ScanditBarcodeScanner//ScanditBarcodeScanner-.aar
      https://repo1.maven.org/maven2//ScanditBarcodeScanner//ScanditBarcodeScanner-.pom
      https://repo1.maven.org/maven2//ScanditBarcodeScanner//ScanditBarcodeScanner-.aar
      file:/SCM/MobileApp/platforms/android/app/libs/ScanditBarcodeScanner-.aar
      file:/SCM/MobileApp/platforms/android/app/libs/ScanditBarcodeScanner.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by moritzhartmeier** [comment]
Hi @avnish90 

You're missing the aar somehow. Is it possible that you downloaded just this repository or added the repository directly? The repository does not contain the aar or a way to fetch it, the 5.x releases for cordova have to be downloaded from your Scandit account as only there do they contain the aar.

**Comment by avnish90** [comment]
@moritzhartmeier Thanks for your quick response, but I have downloaded 5.x release for cordova from my Scandit account

**Comment by moritzhartmeier** [comment]
Hm, that's odd then. It should be in the filesystem at `file:/Users/synerzip/SCM/MobileApp/platforms/android/app/libs/ScanditBarcodeScanner.aar`, the fact that it isn't there would then mean that something went wrong during the installation of the plugin. So i would suggest first removing the plugin again and then readd it and see whether there are any error messages. If nothing obvious shows up, i think we would need the project (or a minimal version of it) where this is reproducible so we can look into it.

**Comment by avnish90** [comment]
@moritzhartmeier Again downloaded 5.x release for Cordova but directory didn't content package.json file.

**Comment by moritzhartmeier** [comment]
Is that something you noticed now or something that the plugin install complained about? Just to check i downloaded both the 5.13.3 and 5.14.0BETA1 cordova packages and they both contain a package.json although I am pretty positive that a package.json is not actually needed for the plugin to work, it would just be needed for npm distribution which only started with 6.1.0. What version are you downloading? How is the archive named that you're trying to use?

**Comment by avnish90** [comment]
Hi @moritzhartmeier,  Downloaded "scandit-barcodescanner-phonegap_5.0.1.zip".

**Comment by moritzhartmeier** [comment]
@avnish90 any reason why you are downloading 5.0.1? That's a very old version (like 2 years old), please get the newest stable release (5.13.3) instead. Alternatively you might also want to try the 6.2 beta which is the absolutely newest release, be aware that it is still a beta but the 6.2 production will come out in about 2 weeks so if you are starting from scratch here i would recommend directly using 6.2 as it has a new and improved API and it will enable you to do things that the 5.x releases are not capable of.

**Comment by avnish90** [comment]
Downloaded 5.13.3, it's working fine in iOS but facing below error while Android build.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
 FAILED
25 actionable tasks: 1 executed, 24 up-to-date
 /SCM/MobileApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
 /.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/46e19d4506505b68270748cc95ab4221/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
    
 /.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/46e19d4506505b68270748cc95ab4221/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
    
 /SCM/MobileApp/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:101: error: resource android:attr/fontVariationSettings not found.
 /SCM/MobileApp/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:101: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
        ... 41 more
Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by moritzhartmeier** [comment]
The old version probably fails because it was done for a much earlier cordova version and something changed in between.

For the new version I assume this has something to do with your current project and cordova itself. I found some similar issues through google:
- https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/207
- https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found

And the solution is to update the compile sdk version:
```
compileSdkVersion 28
```
