### ISSUE TITLE
Cannot read property 'worldFacing' of undefined

### ISSUE THREAD

**Issue by talhagrocerkey** [Scandit/barcodescanner-sdk-cordova#271]
I am facing this issue when I run this on android I am checking for torch availability  `camera.isTorchAvailable` this works fine for iOS but on android I get the following error on the line where I am checking `camera.isTorchAvailable`. 
I am using `scandit-datacapture-cordova-6.4.2.zip`

```
sentry-cordova.bundle.js:5308 ERROR [app-router] Error: Error invoking BarcodeScanner. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot read property 'worldFacing' of undefined
Inner Error Stack:
TypeError: Cannot read property 'worldFacing' of undefined
    at Camera.get isTorchAvailable [as isTorchAvailable] (http://myapp.local/plugins/scandit-cordova-datacapture-core/www/js/Camera.js:57:67)
    at BarcodeScanner.initializeScandit (http://myapp.local/js/app.bundle.js:10023:48)
    at new BarcodeScanner (http://myapp.local/js/app.bundle.js:10003:18)
    at Object.invoke (http://myapp.local/js/vendors-app.bundle.js:2187:24)
    at InvocationHandler.push.3U8n.InvocationHandler.invoke (http://myapp.local/js/vendors-app.bundle.js:2160:28)
    at Container.push.3U8n.Container.invoke (http://myapp.local/js/vendors-app.bundle.js:2346:28)
    at ProviderResolver.get (http://myapp.local/js/vendors-app.bundle.js:52673:72)
    at Container.push.3U8n.Container.get (http://myapp.local/js/vendors-app.bundle.js:2301:28)
    at Container.elementContainerGet [as get] (http://myapp.local/js/vendors-app.bundle.js:52728:15)
    at HtmlBehaviorResource.create (http://myapp.local/js/vendors-app.bundle.js:54754:56)
    at applyInstructions (http://myapp.local/js/vendors-app.bundle.js:52838:31)
    at ViewFactory.create (http://myapp.local/js/vendors-app.bundle.js:53059:7)
    at HtmlBehaviorResource.create (http://myapp.local/js/vendors-app.bundle.js:54766:39)
    at http://myapp.local/js/vendors-app.bundle.js:45765:55
    at http://myapp.local/js/vendors-app.bundle.js:8106:13
    at run (http://myapp.local/js/vendors-app.bundle.js:36702:13)
    at runIfPresent (http://myapp.local/js/vendors-app.bundle.js:36731:21)
    at onGlobalMessage (http://myapp.local/js/vendors-app.bundle.js:36771:17)
End Inner Error Stack
```

**Comment by ScanditSupport** [comment]
Hi @talhagrocerkey,

it seems to be a specific issue and our Support team is happy to help you. Please file a request via 
https://support.scandit.com/hc/en-us/requests/new 

Best regards
Scandit Support
